# Generated by Django 4.2.27 on 2026-01-06 16:11

from django.db import migrations, models
from pgvector.django import VectorField
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='link',
            name='embedding',
            field=VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기중'), ('PROCESSING', '처리중'), ('COMPLETED', '완료'), ('FAILED', '실패'), ('PARTIAL', '일부완료')], default='PENDING', max_length=20),
        ),
    ]
