# Generated by Django 4.2.27 on 2026-01-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기중'), ('PROCESSING', '처리중'), ('COMPLETED', '완료'), ('FAILED', '실패'), ('PARTIAL', '일부완료'), ('RECOMMENDED', 'AI추천')], default='PENDING', max_length=20),
        ),
    ]
