# Generated by Django 4.2.27 on 2026-01-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_link_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='recommendation_type',
            field=models.CharField(blank=True, choices=[('PERSONAL', '관심사 기반'), ('EXPLORE', '탐험')], db_index=True, max_length=20, null=True),
        ),
    ]
