# Generated by Django 4.2.27 on 2026-01-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_link_recommendation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stats_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stats_snapshot_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
